### ISSUE TITLE
Tray support

### ISSUE THREAD

**Issue by rollecode** [paolo257428/WaterDrops#1]
Awesome app! It's not clear to me does the app stay in the background as service because I see no waterdrops logo in the tray area. Is it possible to have tray support? Do I have to keep it in the task bar at all times if I want to get reminded?

**Comment by rollecode** [comment]
So I read the readme: Works as a background task when minimized ✔️

Minimized only? Not if closed from X?

**Comment by pgallo725** [comment]
Hi, thanks for your interest!

When I developed the app I was looking for ways to make it work as a tray process, but as far as I understood UWP apps cannot work in the system tray since that's exclusive to Win32 (also because UWP is cross-platform with Xbox and Windows Phone, which don't have a tray).
So unfortunately you'd need to keep it minimized in the taskbar in order to have it working in the background.
